package com.example.ooprpg.command;

public enum CommandPool {
    NEW_GAME, MAIN_PAGE, START_GAME, CONTINUE, HELICOPTER,
    LOSE, WIN, MAKE_RGR, BUY_DIPLOMA, OVERSLEEP,
    BUY_A_DIPLOMA, PLAY_DOTA, FALL_ASLEEP,
    EAT_SHAWARMA, DRINK_TEA,
    POSTCARDS, SING_AT_POLYANA, EPAM, IT_STEP
}
